name = "ShiftedArrays"
uuid = "1277b4bf-5013-50f5-be3d-901d8477a67a"
repo = "https://github.com/piever/ShiftedArrays.jl.git"
version = "0.5.1"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[compat]
OffsetArrays = "0.9, 0.10, 0.11"
RecursiveArrayTools = "0, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
